title: "Helge Fredriksen"
email: helge.fredriksen@uit.no
description: >-
  Academic profile of Helge Fredriksen.
baseurl: "" 
url: "https://helgeingvart.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache

   
# Enable academicons
enable:
  academicons: true
    
minimal_mistakes_skin: "default"
locale: "en-US"

author:
  name   : "Helge Fredriksen"
  avatar : "/assets/images/profile.jpg"
  bio    : "Associate Professor at UiT focusing on machine learning, generative AI, and applications in space, maritime and clinical sectors."
  email  : "helge.fredriksen@uit.no"
  uri    : "https://en.uit.no/ansatte/helge.fredriksen"
  links  :
    - label: "Google Scholar"
      icon: "ai ai-google-scolar"
      url: "https://scholar.google.no/citations?user=WrY7rgoAAAAJ&hl=no"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-3974-9583"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/helgeingvart"
    - label: "UIT Profile"
      icon: "fas fa-university"
      url: "https://en.uit.no/ansatte/helge.fredriksen"

include: ["_pages"]
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
